model:
  channel_in: 1
  num_hiddens: 128
  num_res_layers: 2
  num_res_hiddens: 32
  codebook_size: 512
  embedding_dim: 64
  commitment_cost: 0.25

data:
  path: 'data/qm9'
  name: 'qm9'
  train_split: 0.1
  valid_split: 0.05
  test_split:  0.05

train:
  epochs: 10
  batch_size: 64
  lr: 0.001
  checkpoint_dir: './checkpoints'
