### MODEL HYPERPARAMETERS ###
vqvgae:
  encoder:
    n_layers: 3
    hidden_dim: 128
    emb_dim: 32
  quantizer:
    codebook_size: 4096
    emb_dim: 8
    commitment_cost: 0.25
    init_steps: 0
    collect_desired_size: 0
    scales:
      - 1
      - 2
      - 3
  latent_attn_proj:
    n_layers: 3
    n_heads: 4
  decoder:
    n_layers: 3
    hidden_dim: 128
    emb_dim: 32

var:
  depth: 4
  num_heads: 4
  emb_dim: 256
  num_classes: 40


### TRAINING HYPERPARAMETERS ###
train:
  vqvgae:
    epochs: 60
    batch_size: 64

    lr: 0.001
    lr_decay: 0.5
    decay_iter: 12000

    beta1: 0.9
    beta2: 0.99
    gamma: 0.1
    sch_patience: 4
  var:
    epochs: 5
    batch_size: 128
    lr: 0.00
    lr_decay: 0.5
    beta1: 0.9
    beta2: 0.99
    sch_patience: 3
    grad_clip: 2.0
    label_smooth: 0.0
    mlp_ratio: 4.0


### DATASET ###
dataset:
  name: qm9                     # Must be lower case 'qm9' or 'zinc'
  debug: true
  n_exp_samples: 1024

qm9:
  path: 'data/qm9'
  node_feature_dim: 4           # Original node features
  additional_node_features: 5   # +5 for Spectral Features
  edge_feature_dim: 3
  max_gsize: 12

zinc:
  path: 'data/zinc'
  node_feature_dim: 9           # Original node features
  additional_node_features: 5   # +5 for Spectral Features
  edge_feature_dim: 3
  max_gsize: 40


### LOG SETTINGS ###
log:
  checkpoint_dir: './checkpoints'
  log_loss_per_n_epoch: 1