model:
  channel_in: 1
  num_hiddens: 128
  num_res_layers: 2
  num_res_hiddens: 32
  codebook_size: 512
  embedding_dim: 64
  commitment_cost: 0.25

data:
  path: 'data/Mutagenicity'
  name: 'Mutagenicity'
  train_split: 0.8

train:
  epochs: 2
  batch_size: 64
  lr: 0.001
  checkpoint_dir: './checkpoints'
