vqvgae:
  encoder:
    n_layers: 4
    hidden_dim: 128
    emb_dim: 32
  decoder:
    n_layers: 4
    hidden_dim: 128
    emb_dim: 32
  quantizer:
    codebook_size: 1024
    emb_dim: 8
    commitment_cost: 0.25
    init_steps: 1_000
    collect_desired_size: 100_000
    scales:
      - 1
      - 2
      - 3 
      - 4 
      - 6 
      - 9 
      - 13 
      - 18 
      - 24 
      - 32
  train:
    epochs: 10
    batch_size: 32
    lr: 0.001
    lr_decay: 0.5
    beta1: 0.9
    beta2: 0.99
    gamma: 0.1
    lr_decay: 0.8
    sch_patience: 4

var:
  depth: 8
  num_heads: 8
  emb_dim: 256
  num_classes: 10
  train:
    epochs: 25
    batch_size: 32
    lr: 0.001
    lr_decay: 0.5
    beta1: 0.9
    beta2: 0.99
    lr_decay: 0.8
    sch_patience: 4
    grad_clip: 2.0
    label_smooth: 0.0

data:
  path: 'data/qm9'
  train_val_test_split: [0.8, 0.2, 0.0]
  dataset_size: null
  node_feature_dim: 11          # Original node features
  additional_node_features: 5   # +5 for Spectral Features
  edge_feature_dim: 4

log:
  checkpoint_dir: './checkpoints'
  log_loss_per_n_epoch: 1