model:
  encoder:
    n_layers: 4
    hidden_dim: 128
    emb_dim: 32
  decoder:
    n_layers: 4
    hidden_dim: 128
    emb_dim: 32
  quantizer:
    codebook_size: 1024
    emb_dim: 8
    commitment_cost: 0.25
    init_steps: 100
    collect_desired_size: 5_000

data:
  path: 'data/qm9'
  name: 'qm9'
  train_val_test_split: [0.8, 0.1, 0.1]
  dataset_size: 10_000
  node_feature_dim: 11
  edge_feature_dim: 4

train:
  epochs: 250
  batch_size: 32
  lr: 0.001
  lr_decay: 0.5
  decay_iteration: 25000
  beta1: 0.9
  beta2: 0.99
  checkpoint_dir: './checkpoints'
  gamma: 0.1